import type { Metadata } from "next";
import { Syncopate,Poppins ,Roboto } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Add the weights you need
  variable: '--font-roboto',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Choose the weights you need
  variable: '--font-poppins',
});


const syncopate = Syncopate({
  variable: "--font-syncopate",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Coffee App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${syncopate.variable} ${poppins.variable} ${roboto.variable} `}>
      <body
       
      >
        {children}
      </body>
    </html>
  );
}
